name: Cypress Test
on: [push]
jobs : 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v3.0.0
        with:
          start: npm start
